export const COBOL_SPECS = {
  COLUMNS: {
    SEQUENCE_END: 6,
    INDICATOR: 6, // 0-indexed column 7 is index 6
    AREA_A_START: 7, // 0-indexed column 8 is index 7
    AREA_A_END: 11, // 0-indexed column 11 is index 10 (length 4)
    AREA_B_START: 11, // 0-indexed column 12 is index 11
    AREA_B_END: 72,
    MAX_LINE_LENGTH: 72,
  },
  INDICATORS: [' ', '*', '/', '-', 'D', 'd'],
  MANDATORY_DIVISIONS: ['IDENTIFICATION DIVISION'],
  MANDATORY_PARAGRAPHS: ['PROGRAM-ID'],
  ALL_DIVISIONS: [
    'IDENTIFICATION DIVISION',
    'ENVIRONMENT DIVISION',
    'DATA DIVISION',
    'PROCEDURE DIVISION',
  ],
  ALL_SECTIONS: [
    'CONFIGURATION SECTION',
    'INPUT-OUTPUT SECTION',
    'FILE SECTION',
    'WORKING-STORAGE SECTION',
    'LOCAL-STORAGE SECTION',
    'LINKAGE SECTION',
    'SCREEN SECTION',
  ],
  AREA_A_LEVELS: ['01', '77', '78', '66', 'FD', 'SD', 'RD'],
  AREA_B_STATEMENTS: [
    'ACCEPT',
    'ADD',
    'ALTER',
    'CALL',
    'CANCEL',
    'CLOSE',
    'COMPUTE',
    'CONTINUE',
    'DELETE',
    'DISPLAY',
    'DIVIDE',
    'EVALUATE',
    'EXIT',
    'GOBACK',
    'IF',
    'INITIALIZE',
    'INSPECT',
    'MERGE',
    'MOVE',
    'MULTIPLY',
    'OPEN',
    'PERFORM',
    'READ',
    'RELEASE',
    'RETURN',
    'REWRITE',
    'SEARCH',
    'SET',
    'SORT',
    'START',
    'STOP',
    'STRING',
    'SUBTRACT',
    'UNSTRING',
    'WRITE',
    'END-IF',
    'END-PERFORM',
    'END-EVALUATE',
    'END-READ',
    'END-WRITE',
    'END-COMPUTE',
    'END-CALL',
    'ELSE',
    'WHEN',
  ],
  DATA_CLAUSES: [
    'PIC',
    'PICTURE',
    'VALUE',
    'COMP',
    'COMP-3',
    'USAGE',
    'OCCURS',
    'REDEFINES',
  ],
  ARITHMETIC_STATEMENTS: [
    'ACCEPT',
    'ADD',
    'SUBTRACT',
    'MULTIPLY',
    'DIVIDE',
    'COMPUTE',
    'MOVE',
    'DISPLAY',
    'IF',
    'EVALUATE',
  ],
  RESERVED_WORDS: new Set([
    'ACCEPT',
    'ADD',
    'SUBTRACT',
    'MULTIPLY',
    'DIVIDE',
    'COMPUTE',
    'MOVE',
    'DISPLAY',
    'IF',
    'EVALUATE',
    'TO',
    'FROM',
    'BY',
    'INTO',
    'GIVING',
    'REMAINDER',
    'ROUNDED',
    'ON',
    'SIZE',
    'ERROR',
    'NOT',
    'THEN',
    'ELSE',
    'END-ADD',
    'END-SUBTRACT',
    'END-MULTIPLY',
    'END-DIVIDE',
    'END-COMPUTE',
    'END-IF',
    'END-EVALUATE',
    'WHEN',
    'OTHER',
    'ALSO',
    'THRU',
    'THROUGH',
    'OR',
    'AND',
    'EQUAL',
    'EQUALS',
    'GREATER',
    'LESS',
    'THAN',
    'ZERO',
    'ZEROS',
    'ZEROES',
    'SPACE',
    'SPACES',
    'HIGH-VALUE',
    'HIGH-VALUES',
    'LOW-VALUE',
    'LOW-VALUES',
    'QUOTE',
    'QUOTES',
    'ALL',
    'UPON',
    'CONSOLE',
    'LINE',
    'POSITION',
    'ADVANCING',
    'PAGE',
    'EOF',
    'IS',
    'NUMERIC',
    'ALPHABETIC',
  ]),
}

export const JCL_SPECS = {
  PREFIXES: ['//', '/*'],
  MAX_NAME_LENGTH: 8,
  NAME_PATTERN: /^[A-Z#$@][A-Z0-9#$@]*$/,
  VALID_OPERATIONS: [
    'JOB',
    'EXEC',
    'DD',
    'PROC',
    'PEND',
    'SET',
    'INCLUDE',
    'IF',
    'THEN',
    'ELSE',
    'ENDIF',
    'OUTPUT',
    'JCLLIB',
  ],
  DISP_SUBPARAMETERS: [
    'NEW',
    'OLD',
    'SHR',
    'MOD',
    'KEEP',
    'DELETE',
    'PASS',
    'CATLG',
    'UNCATLG',
  ],
}
